import pyfirmata
import time
board = pyfirmata.Arduino('COM3')
board.digital[13].write(1)
board.digital[8].write(1)
time.sleep(0.7)
board.digital[13].write(0)
board.digital[8].write(0)
board.digital[12].write(1)
board.digital[10].write(1)
board.digital[9].write(1)
time.sleep(0.7)
board.digital[12].write(0)
board.digital[10].write(0)
board.digital[9].write(0)
board.digital[11].write(1)
board.digital[10].write(1)
time.sleep(0.7)
board.digital[11].write(0)
board.digital[10].write(0)