import tkinter as tk
win = tk.Tk()
win.title("Calculator v0")
maincalc= tk.Entry(width=50)

bt1 = tk.Button(text="1",command = maincalc.insert(0,"1"))
bt2 = tk.Button(text="2",command = maincalc.insert(0,"2"))
bt3 = tk.Button(text="3",command = maincalc.insert(0,"3"))
bt4 = tk.Button(text="4",command = maincalc.insert(0,"4"))
bt5 = tk.Button(text="5",command = maincalc.insert(0,"5"))
bt6 = tk.Button(text="6",command = maincalc.insert(0,"6"))
bt7 = tk.Button(text="7",command = maincalc.insert(0,"7"))
bt8 = tk.Button(text="8",command = maincalc.insert(0,"8"))
bt9 = tk.Button(text="9",command = maincalc.insert(0,"9"))
bt0 = tk.Button(text="0",command = maincalc.insert(0,"0"))
bts1 = tk.Button(text="+",command = maincalc.insert(1,"+"))
bts2 = tk.Button(text="-",command = maincalc.insert(1,"-"))
bts3 = tk.Button(text="=")
maincalc.pack()
bt1.pack()
bt2.pack()
bt3.pack()
bt4.pack()
bt5.pack()
bt6.pack()
bt7.pack()
bt8.pack()
bt9.pack()
bt0.pack()
bts1.pack()
bts2.pack()
bts3.pack()
win.mainloop()

